---
title: "Keras_MNIST"
author: "Marian Dumitrascu"
date: "April 4, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keras)
```

## Leearning Keras

https://keras.rstudio.com/#tutorials

```{r}
mnist <- dataset_mnist()
```

```{r}
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y


x_train <- keras::array_reshape(x_train, c(nrow(x_train), 784))
x_test <- keras::array_reshape(x_test, c(nrow(x_test), 784))

# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- keras::to_categorical(y_train, 10)
y_test <- keras::to_categorical(y_test, 10)

```



## Definee the Model

```{r}

model_fit <- keras::keras_model_sequential()
model_fit %>% 
	layer_dense(units = 256, activation = "relu", input_shape = c(784), name = "layer_one") %>% 
	layer_dropout(rate = 0.4) %>% 
	layer_dense(units = 128, activation = "relu") %>% 
	layer_dropout(rate = 0.3) %>% 
	layer_dense(units = 10, activation = "softmax")

summary(model_fit)


```

## Compile

```{r}
model_fit %>% 
	compile(
		loss = "categorical_crossentropy",
		optimizer = optimizer_rmsprop(),
		metrics = c("accuracy")
	)
summary(model_fit)
```

## Training and Evaluation

```{r}
history <- model_fit %>% 
	fit(
		x_train, 
		y_train,
		epochs = 30, 
		batch_sizee = 128,
		validation_split = 0.2
		)
plot(history)

```



## Evaluate

```{r}

model_fit %>% keras::evaluate(x_test, y_test)

```

## Generatee Predictions on New Data

```{r}
prediction <- model_fit %>% keras::predict_classes(x_test)
head(prediction)

```






